"""add rubric_scores to feedback

Revision ID: 535ab26448f6
Revises: d7bcb7f19d11
Create Date: 2026-04-09 18:57:24.398692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535ab26448f6'
down_revision: Union[str, Sequence[str], None] = 'd7bcb7f19d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_list', sa.Column('rubric_scores', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_list', 'rubric_scores')
    # ### end Alembic commands ###
