"""feedback

Revision ID: 53cbeebda8b7
Revises: d19992a674b5
Create Date: 2026-03-09 22:14:50.646458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cbeebda8b7'
down_revision: Union[str, Sequence[str], None] = 'd19992a674b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_list', sa.Column('grade', sa.Float(), nullable=True))
    op.add_column('feedback_list', sa.Column('ai_generated', sa.Boolean(), nullable=True))
    op.add_column('feedback_list', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('feedback_list', sa.Column('released', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_list', 'released')
    op.drop_column('feedback_list', 'status')
    op.drop_column('feedback_list', 'ai_generated')
    op.drop_column('feedback_list', 'grade')
    # ### end Alembic commands ###
