"""rubric

Revision ID: 576a27b681ae
Revises: d76ff3f65a4c
Create Date: 2026-03-10 00:42:08.016102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576a27b681ae'
down_revision: Union[str, Sequence[str], None] = 'd76ff3f65a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rubrics', sa.Column('assignment_id', sa.Integer(), nullable=False))
    op.add_column('rubrics', sa.Column('criteria', sa.JSON(), nullable=False))
    op.add_column('rubrics', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'rubrics', ['assignment_id'])
    op.create_foreign_key(None, 'rubrics', 'assignment_list', ['assignment_id'], ['assignment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rubrics', type_='foreignkey')
    op.drop_constraint(None, 'rubrics', type_='unique')
    op.drop_column('rubrics', 'created_at')
    op.drop_column('rubrics', 'criteria')
    op.drop_column('rubrics', 'assignment_id')
    # ### end Alembic commands ###
