"""add submission table

Revision ID: 5802944c11c1
Revises: f6f29635a075
Create Date: 2026-02-19 18:55:33.880047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5802944c11c1'
down_revision: Union[str, Sequence[str], None] = 'f6f29635a075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grade_list', 'approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grade_list', 'approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
