"""add submission table

Revision ID: 6b74dbc8697a
Revises: 71228b2a45c7
Create Date: 2026-02-19 15:28:20.178373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b74dbc8697a'
down_revision: Union[str, Sequence[str], None] = '71228b2a45c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_list', sa.Column('file_name', sa.String(), nullable=False))
    op.drop_column('submission_list', 'code_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_list', sa.Column('code_file', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('submission_list', 'file_name')
    # ### end Alembic commands ###
