"""add submissions table

Revision ID: 905d86b221e8
Revises: b0da798008b5
Create Date: 2026-02-19 15:16:29.511821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905d86b221e8'
down_revision: Union[str, Sequence[str], None] = 'b0da798008b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_list', sa.Column('assignment_id', sa.Integer(), nullable=False))
    op.add_column('submission_list', sa.Column('student_id', sa.String(), nullable=False))
    op.add_column('submission_list', sa.Column('code_file', sa.String(), nullable=False))
    op.add_column('submission_list', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('submission_list', sa.Column('file_type', sa.String(), nullable=False))
    op.add_column('submission_list', sa.Column('submitted_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'submission_list', 'assignment_list', ['assignment_id'], ['assignment_id'])
    op.create_foreign_key(None, 'submission_list', 'students', ['student_id'], ['matric_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission_list', type_='foreignkey')
    op.drop_constraint(None, 'submission_list', type_='foreignkey')
    op.drop_column('submission_list', 'submitted_at')
    op.drop_column('submission_list', 'file_type')
    op.drop_column('submission_list', 'file_path')
    op.drop_column('submission_list', 'code_file')
    op.drop_column('submission_list', 'student_id')
    op.drop_column('submission_list', 'assignment_id')
    # ### end Alembic commands ###
