"""add submission table

Revision ID: 97f720087a25
Revises: d2d72b5ac60c
Create Date: 2026-02-19 18:14:55.720319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f720087a25'
down_revision: Union[str, Sequence[str], None] = 'd2d72b5ac60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade_list', sa.Column('student_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'grade_list', 'students', ['student_id'], ['matric_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grade_list', type_='foreignkey')
    op.drop_column('grade_list', 'student_id')
    # ### end Alembic commands ###
