"""initial

Revision ID: b0da798008b5
Revises: 
Create Date: 2026-02-19 14:37:59.555619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0da798008b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('student_subjects')
    op.drop_table('lecturer_subjects')
    op.drop_table('subjects')
    op.add_column('assignment_list', sa.Column('course_name', sa.String(), nullable=False, server_default=''))
    op.alter_column('assignment_list', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_assignment_list_assignment_id'), 'assignment_list', ['assignment_id'], unique=False)
    op.create_foreign_key(None, 'assignment_list', 'lecturers', ['lecturer_id'], ['lecturer_id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('STUDENT', 'LECTURER', 'ADMINISTRATOR', name='userrole'),
               existing_nullable=False,
               postgresql_using="role::userrole")  # ← this fixes the cast error
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'LECTURER', 'ADMINISTRATOR', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'assignment_list', type_='foreignkey')
    op.drop_index(op.f('ix_assignment_list_assignment_id'), table_name='assignment_list')
    op.alter_column('assignment_list', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_column('assignment_list', 'course_name')
    op.create_table('student_subjects',
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.matric_no'], name=op.f('student_subjects_student_id_fkey')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name=op.f('student_subjects_subject_id_fkey')),
    sa.PrimaryKeyConstraint('student_id', 'subject_id', name=op.f('student_subjects_pkey'))
    )
    op.create_table('lecturer_subjects',
    sa.Column('lecturer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.lecturer_id'], name=op.f('lecturer_subjects_lecturer_id_fkey')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name=op.f('lecturer_subjects_subject_id_fkey')),
    sa.PrimaryKeyConstraint('lecturer_id', 'subject_id', name=op.f('lecturer_subjects_pkey'))
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('subject_id', name=op.f('subjects_pkey')),
    sa.UniqueConstraint('name', name=op.f('subjects_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
