"""change something in models (feedbackout)

Revision ID: d19992a674b5
Revises: 2ef0a6df918c
Create Date: 2026-02-21 16:44:12.903250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19992a674b5'
down_revision: Union[str, Sequence[str], None] = '2ef0a6df918c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_list', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('feedback_list', sa.Column('areas_for_improvement', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_list', 'areas_for_improvement')
    op.drop_column('feedback_list', 'strengths')
    # ### end Alembic commands ###
