"""add submission table

Revision ID: d2d72b5ac60c
Revises: 6b74dbc8697a
Create Date: 2026-02-19 17:47:49.057871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d72b5ac60c'
down_revision: Union[str, Sequence[str], None] = '6b74dbc8697a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade_list', sa.Column('submission_id', sa.Integer(), nullable=False))
    op.add_column('grade_list', sa.Column('final_score', sa.Float(), nullable=True))
    op.add_column('grade_list', sa.Column('approved', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'grade_list', 'submission_list', ['submission_id'], ['submission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grade_list', type_='foreignkey')
    op.drop_column('grade_list', 'approved')
    op.drop_column('grade_list', 'final_score')
    op.drop_column('grade_list', 'submission_id')
    # ### end Alembic commands ###
