"""some upgrades

Revision ID: d7bcb7f19d11
Revises: 576a27b681ae
Create Date: 2026-04-09 03:27:25.906972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7bcb7f19d11'
down_revision: Union[str, Sequence[str], None] = '576a27b681ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_list', sa.Column('question_file_name', sa.String(), nullable=True))
    op.add_column('assignment_list', sa.Column('question_file_path', sa.String(), nullable=True))
    op.add_column('assignment_list', sa.Column('question_file_type', sa.String(), nullable=True))
    op.add_column('rubrics', sa.Column('rubric_file_name', sa.String(), nullable=True))
    op.add_column('rubrics', sa.Column('rubric_file_path', sa.String(), nullable=True))
    op.add_column('rubrics', sa.Column('rubric_file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rubrics', 'rubric_file_type')
    op.drop_column('rubrics', 'rubric_file_path')
    op.drop_column('rubrics', 'rubric_file_name')
    op.drop_column('assignment_list', 'question_file_type')
    op.drop_column('assignment_list', 'question_file_path')
    op.drop_column('assignment_list', 'question_file_name')
    # ### end Alembic commands ###
